export const AUTH_REQUEST="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const LOGOUT="LOGOUT";

export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const CLEAR_CART="CLEAR_CART";

export const FETCH_PRO_REQUEST="FETCH_PRO_REQUEST";
export const FETCH_PRO_SUCCESS="FETCH_PRO_SUCCESS";
export const FETCH_PRO_FAIL="FETCH_PRO_FAIL";
